### ISSUE TITLE
getDownloadUrl no longer working

### ISSUE THREAD

**Issue by wdaguno** [mitchtabian/TabianConsulting#2]
Hi Mitch,

   On the IssuesPhotoUploader, the getDownloadUrl no longer usable. What alternative have you been using since? 

Thanks!

**Comment by mitchtabian** [comment]
There is a link in the comments of the Pluralsight course

**Comment by wdaguno** [comment]
I saw it! Thanks Mitch!

**Comment by mitchtabian** [comment]
No problem.
